pipeline {
    agent any

    tools {
        //jdk 'JDK8'          // IMPORTANT: Java 1.8 dans ton pom.xml
        maven 'Maven3'       // Nom configuré dans Jenkins
    }

    environment {
        APP_NAME = "achat"
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'badiss',
                    url: 'https://github.com/GhassenAhmed/DevOps'
            }
        }

        stage('Build') {
            steps {
                dir('achat/achat') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Tests') {
            steps {
                dir('achat/achat') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('achat/achat') {
                    withSonarQubeEnv('SonarQube') {
                        sh 'mvn sonar:sonar -Dsonar.projectKey=achat -Dsonar.projectName=achat'
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('achat/achat') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

stage('Nexus Deploy') {
    steps {
        dir('achat/achat') {
            withCredentials([usernamePassword(
                credentialsId: 'nexus-credentials',
                usernameVariable: 'NEXUS_USER',
                passwordVariable: 'NEXUS_PASS'
            )]) {
                sh """
                    mvn deploy -DskipTests \
                      -DaltDeploymentRepository=nexus::default::http://\${NEXUS_USER}:\${NEXUS_PASS}@localhost:8081/repository/maven-snapshots/
                """
            }
        }
    }
}
stage('OWASP Dependency Check') {
    steps {
        dir('achat/achat') {
            withCredentials([string(
                credentialsId: 'nvd-api-key',
                variable: 'NVD_API_KEY'
            )]) {
                sh 'mvn dependency-check:check -DnvdApiKey=$NVD_API_KEY'
            }
        }
    }
    post {
        always {
            publishHTML(target: [
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'achat/achat/target',
                reportFiles: 'dependency-check-report.html',
                reportName: 'OWASP Dependency Check Report'
            ])
        }
    }
}


    }

    post {
        success {
            echo 'Build réussi 🎉'
        }
        failure {
            echo 'Build échoué ❌'
        }
        always {
            echo 'Pipeline terminé'
        }
    }
}